export const STORE_USER_INFO = 'STORE_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const DELETE_USER_INFO = 'DELETE_USER_INFO'


export const STORE_AISKILLGROUP_DATA = 'STORE_AISKILLGROUP_DATA'
export const CREATE_AISKILLGROUP_DATA = 'CREATE_AISKILLGROUP_DATA'
export const UPDATE_AISKILLGROUP_DATA = 'UPDATE_AISKILLGROUP_DATA'
export const DELETE_AISKILLGROUP_DATA = 'DELETE_AISKILLGROUP_DATA'

export const STORE_FACEGROUP_DATA = 'STORE_FACEGROUP_DATA'
export const CREATE_FACEGROUP_DATA = 'CREATE_FACEGROUP_DATA'
export const UPDATE_FACEGROUP_DATA = 'UPDATE_FACEGROUP_DATA'
export const DELETE_FACEGROUP_DATA = 'DELETE_FACEGROUP_DATA'

export const CREATE_CAMERAGROUP_DATA = 'CREATE_CAMERAGROUP_DATA'
export const STORE_CAMERAGROUP_DATA = 'STORE_CAMERAGROUP_DATA'
export const UPDATE_CAMERAGROUP_DATA = 'UPDATE_CAMERAGROUP_DATA'
export const DELETE_CAMERAGROUP_DATA = 'DELETE_CAMERAGROUP_DATA'

export const ISSCROLLTOBOTTOM = 'ISSCROLLTOBOTTOM'